import { Header } from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "FESTA",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
